services:
  suno-tool:
    build: .
    ports:
      - "3030:3000"
    volumes:
      - ./original_manager:/app/original_manager
      - ./queue.txt:/app/queue.txt
      - ./cookies.txt:/app/cookies.txt
    restart: unless-stopped
